### ISSUE TITLE
FBI OPEN UP!!!

### ISSUE THREAD

**Issue by XynoxTheDev** [anurag3301/anurag3301#1]
![fbi open up](https://tenor.com/view/fbi-fbi-open-the-door-enter-swat-gif-16075253)
https://tenor.com/view/fbi-fbi-open-the-door-enter-swat-gif-16075253

**Comment by anurag3301** [comment]
Aise add karna hota hai 
![fbi open up](https://c.tenor.com/ZvMZoQy5hkMAAAAC/fbi-fbi-open-the-door.gif)
